PROGRAM array01
  IMPLICIT NONE

  INTEGER, PARAMETER :: N = 6;
  INTEGER, PARAMETER :: &
    & PR = SELECTED_REAL_KIND(10,99)

  INTEGER, DIMENSION(:), ALLOCATABLE :: v1, v2
  
  PRINT *, ALLOCATED(v1), SHAPE( v1 ), v1
    
  v1 = (/ -3, -2, -1, 0, 1, 2/)
  
  PRINT *, ALLOCATED(v1), SHAPE( v1 ), v1
  
  DEALLOCATE( v1 )
  PRINT *, ALLOCATED(v1), SHAPE( v1 ), v1
  
END PROGRAM

